# Generated by Django 3.2.6 on 2021-09-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('battery', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('top_speed', models.FloatField()),
                ('distance', models.IntegerField()),
                ('efficiency', models.FloatField()),
                ('fast_charge', models.FloatField()),
                ('price_usd', models.FloatField()),
            ],
        ),
    ]
